* Introduction
  This is a Vagrant project to quickly setup a virtual machine with a ready-to-install ZenPhoto instance.

  This project uses [[https://www.vagrantup.com/docs/multi-machine/][Vagrant multi machine]] feature, therefore two different providers are available:
  - *VirtualBox*: Default with an Ubuntu (14.04) Trusty 64bit virtual machine.
  - *DigitalOcean*: Default with an Ubuntu (14.04) Trusty 64bit virtual machine.

  
* Deployment
  It is possible to deploy on two different providers: Digital Ocean (remote) and VirtualBox (local).

  Create a Vagrantfile from the template:
  #+BEGIN_EXAMPLE
  cp Vagrantfile.default Vagrantfile
  #+END_EXAMPLE

** Remote with Digital Ocean
   - Install Digital Ocean vagrant plugin
     #+BEGIN_EXAMPLE
     vagrant plugin install vagrant-digitalocean
     #+END_EXAMPLE
   - Customize =Vagrantfile= with your Digital Ocean credentials, details [[https://github.com/devopsgroup-io/vagrant-digitalocean][here]] and [[https://www.digitalocean.com/community/tutorials/how-to-use-digitalocean-as-your-provider-in-vagrant-on-an-ubuntu-12-10-vps][here]]
   - Start deployment with
     #+BEGIN_EXAMPLE
     # Provision zenphoto_remote
     vagrant up zenphoto-remote
     #+END_EXAMPLE
   - Visit zenphoto to complete installation at http://DIGITAL_OCEAN_PUBLIC_IP:8080

** Local with VirtualBox
   - Start deployment with
     #+BEGIN_EXAMPLE
     # Provision zenphoto_local
     vagrant up zenphoto_local
     #+END_EXAMPLE
   - Visit zenphoto to complete installation at http://localhost:8080
     
* Notes
  Setup of a ZenPhoto instance using this Vagrant file should be used only for development purposes (on developer laptop) since currently it setup *unsecure ubuntu and mysql* installation 
